### PR TITLE
242 enhance error tracing and logging across the codebase e3

### PR DESCRIPTION
**Pull request by Hermann-Core**

### CODE REVIEW

**Review by ndefokou — CHANGES_REQUESTED** [review]

**Review by ndefokou — COMMENTED** [review]
Good work! After resolving conflicts, I am going to approve.

**Review by Blindspot22 — APPROVED** [review]
LGTM :rocket:

**Review by ndefokou — APPROVED** [review]

**Comment by Christiantyemele** [comment]
please resolve the conflict first @Hermann-Core

**Review by Christiantyemele — COMMENTED** [review]
please resolve the conflicts first

**Review by ndefokou — APPROVED** [review]

**Pull request merged**
