### PR TITLE
41 implement the forward protocol for the pop server

### PR DESCRIPTION
**Pull request by Christiantyemele**

### CODE REVIEW

**Comment by Christiantyemele** [comment]
Hey @IngridPuppet  and @Hermann-Core Please my test is failing because its unable to resolve the random did i gave to it please can you check on this for me

**Comment by Hermann-Core** [comment]
> Hey @IngridPuppet and @Hermann-Core Please my test is failing because its unable to resolve the random did i gave to it please can you check on this for me

Could you clarify where the test is failing? The pipeline appears to be passing without issues.

**Comment by Christiantyemele** [comment]
> > Hey @IngridPuppet and @Hermann-Core Please my test is failing because its unable to resolve the random did i gave to it please can you check on this for me
> 
> Could you clarify where the test is failing? The pipeline appears to be passing without issues.

i am suprised the pipeline passed, if you check out the to branch you will notice the test fails

**Comment by Christiantyemele** [comment]
Hey @Hermann-Core i think the pipeline has issues its not checking the tests

**Comment by Hermann-Core** [comment]
> i am suprised the pipeline passed, if you check out the to branch you will notice the test fails

Screenshot from 2024-09-04 16-56-10

**Pull request closed without merging**
