### PR TITLE
handshake document that gives a description and explanation of the processes found in the handshake flow

### PR DESCRIPTION
**Pull request by Blindspot22**
Please i will love to have a review or comment before any approval. Thank you!

### CODE REVIEW

**Comment by Christiantyemele** [comment]
Hey @Blindspot22 i don't see the difference between the handshake_flow and handshakedoc, and also i though this issue was to bring out the out of band ways of establishing a connection and detailing steps involved

**Comment by Christiantyemele** [comment]
> Hey @Blindspot22 i don't see the difference between the handshake_flow and handshakedoc, and also i though this issue was to bring out the out of band ways of establishing a connection and detailing steps involved

@IngridPuppet can you check if i am right ?

**Comment by Blindspot22** [comment]
> Hey @Blindspot22 i don't see the difference between the handshake_flow and handshakedoc, and also i though this issue was to bring out the out of band ways of establishing a connection and detailing steps involved

 the handshake flow is the actual process or sequence of actions that take place during a handshake, while the handshake documentation is the description and explanation of those processes or rather why they are used or important.

**Comment by Blindspot22** [comment]
> > Hey @Blindspot22 i don't see the difference between the handshake_flow and handshakedoc, and also i though this issue was to bring out the out of band ways of establishing a connection and detailing steps involved
> 
> @IngridPuppet can you check if i am right ?

@Christiantyemele Can you please review this PR again?

**Comment by Blindspot22** [comment]
@ndefokou I'm waiting for your review!

**Review by ndefokou — APPROVED** [review]

**Pull request merged**
