### PR TITLE
Merge pull request #152 from adorsys/main

### PR DESCRIPTION
**Pull request by Blindspot22**
Merging Main branch with branch 99

### CODE REVIEW

**Comment by Christiantyemele** [comment]
i don't understand the use of this PR

**Comment by Blindspot22** [comment]
> i don't understand the use of this PR @Blindspot22

I just did the handshake flow implementation on this branch and merged it successfully with the approval of Francis on the main branch. But my branch is more than 20 commits behind and I'm still to work on the branch.
I'm doing this cause Francis said the branches shouldn't be to behind with commits especially when we are to work on it again.

**Comment by IngridPuppet** [comment]
Hi Scott (@Blindspot22). Yes, as per Mr Francis' recommendation, you should update your local branch periodically, i.e., merging main into your local branch. However, note that opening a PR just to update the main branch with the created merge commit is not required.

There might be other things I'm missing. I'm quoting this sentence:
> But my branch is more than 20 commits behind and I'm still to work on the branch.

1. Can you give more details as to why your branch would be behind main after that?
2. Why keep working on the same branch if it was already merged? Was the linked issue only partially addressed?

**Comment by Blindspot22** [comment]
It's Okay sir. I just reverified the branch again and its to be rather deleted. Thanks for the review @Christiantyemele and @IngridPuppet. The branch I'm still to work on is branch 40

**Pull request closed without merging**
