### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Blindspot22**
Uploading an image which will be used in the README.md file which shows a  demonstration on how the generic server is ran.

### CODE REVIEW

**Comment by Christiantyemele** [comment]
> Uploading an image which will be used in the README.md file which shows a demonstration on how the generic server is ran.

Why not directly do it [here](https://github.com/adorsys/didcomm-mediator-rs/pull/121)

**Comment by Blindspot22** [comment]
> > Uploading an image which will be used in the README.md file which shows a demonstration on how the generic server is ran.
> 
> Why not directly do it [here](https://github.com/adorsys/didcomm-mediator-rs/pull/121)

Because I am working on the browser and not on my machine locally. Working on my machine locally will mark my commits as unverified.

**Comment by Christiantyemele** [comment]
> > > Uploading an image which will be used in the README.md file which shows a demonstration on how the generic server is ran.
> > 
> > 
> > Why not directly do it [here](https://github.com/adorsys/didcomm-mediator-rs/pull/121)
> 
> Because I am working on the browser and not on my machine locally. Working on my machine locally will mark my commits as unverified. And unverified commits have been discouraged in the project. But it's just an image, you can check on the `Files changed` above

i think this might [help](https://github.com/Christiantyemele/GCM_SSH_signing)

**Review by Christiantyemele — CHANGES_REQUESTED** [review]
I don't really see this neccessary what do you think @IngridPuppet

**Comment by Blindspot22** [comment]
> > > > Uploading an image which will be used in the README.md file which shows a demonstration on how the generic server is ran.
> > > 
> > > 
> > > Why not directly do it [here](https://github.com/adorsys/didcomm-mediator-rs/pull/121)
> > 
> > 
> > Because I am working on the browser and not on my machine locally. Working on my machine locally will mark my commits as unverified. And unverified commits have been discouraged in the project. But it's just an image, you can check on the `Files changed` above
> 
> i think this might [help](https://github.com/Christiantyemele/GCM_SSH_signing)

I have done that already on this machine and it didn't work on the Mac Book for some reasons. Anyways today is the last day I will be using the this particular machine here again so I don't think repeating the ssh signing procedure is useful.

**Review by Christiantyemele — APPROVED** [review]

**Pull request merged**
